import { Product } from '../types/product';
import { Customer } from '../types/customer';
import { Invoice } from '../types/invoice';
import { Supplier, PurchaseOrder } from '../types/purchase';
import { LedgerEntry } from '../types/ledger';
import { BusinessProfile } from '../types/settings';

export const initialBusinessProfile: BusinessProfile = {
  storeName: 'OmniTrade Supermart & Wholesale',
  tagline: 'Your Trusted Partner for Bulk & Daily Essentials',
  phone: '+1 (555) 382-9900',
  email: 'contact@omnitrade-hub.com',
  address: '742 Market Boulevard, Commercial District, Metro City 10001',
  taxNumber: 'TAX-US-984210984-A',
  currencySymbol: '',
  currencyCode: 'USD',
  operatingMode: 'hybrid',
  receiptFooterMessage: 'Thank you for your business! Please visit again.',
  bankDetails: {
    bankName: 'First Commercial Reserve Bank',
    accountNumber: '9845-2201-9983-4412',
    accountHolder: 'OmniTrade Commercial Corp.',
    routingOrIfsc: 'FCRB0004921',
  },
};

export const initialProducts: Product[] = [
  {
    id: 'prod-1',
    sku: 'RICE-BAS-05',
    barcode: '8901234567890',
    name: 'Premium Royal Basmati Rice (5kg)',
    description: 'Aged extra long grain basmati rice with fragrant aroma.',
    category: 'Grains & Staple',
    primaryUnit: 'Bag',
    packagingUnit: 'Carton',
    packagingMultiplier: 6, // 1 carton = 6 bags
    costPrice: 9.20,
    retailPrice: 14.50,
    wholesaleTiers: [
      { minQuantity: 6, pricePerUnit: 12.00, label: 'Carton Tier (6+ bags)' },
      { minQuantity: 24, pricePerUnit: 10.75, label: 'Bulk Tier (24+ bags)' },
      { minQuantity: 60, pricePerUnit: 9.95, label: 'Pallet Tier (60+ bags)' },
    ],
    stockQuantity: 180,
    reorderLevel: 30,
    taxRate: 5,
    hsnCode: '1006.30',
    batches: [
      { id: 'b-101', batchNumber: 'LOT-2025-A1', expiryDate: '2027-06-30', quantity: 120, costPrice: 9.00 },
      { id: 'b-102', batchNumber: 'LOT-2025-B2', expiryDate: '2027-09-15', quantity: 60, costPrice: 9.40 },
    ],
    imageUrl: 'https://images.unsplash.com/photo-1586201375761-83865001e31c?w=300&auto=format&fit=crop&q=60',
    active: true,
  },
  {
    id: 'prod-2',
    sku: 'OIL-OLV-1L',
    barcode: '8901234567891',
    name: 'Cold-Pressed Extra Virgin Olive Oil (1L)',
    description: 'First cold pressed Mediterranean single-origin olive oil in glass bottle.',
    category: 'Oils & Condiments',
    primaryUnit: 'Bottle',
    packagingUnit: 'Crate',
    packagingMultiplier: 12, // 1 crate = 12 bottles
    costPrice: 11.50,
    retailPrice: 18.00,
    wholesaleTiers: [
      { minQuantity: 12, pricePerUnit: 14.80, label: 'Case Tier (12+ btl)' },
      { minQuantity: 48, pricePerUnit: 13.50, label: 'Wholesale Tier (48+ btl)' },
      { minQuantity: 120, pricePerUnit: 12.40, label: 'Distributor Tier (120+ btl)' },
    ],
    stockQuantity: 95,
    reorderLevel: 24,
    taxRate: 5,
    hsnCode: '1509.10',
    batches: [
      { id: 'b-201', batchNumber: 'EVOO-884', expiryDate: '2026-12-31', quantity: 95, costPrice: 11.50 },
    ],
    imageUrl: 'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=300&auto=format&fit=crop&q=60',
    active: true,
  },
  {
    id: 'prod-3',
    sku: 'COF-ARB-500',
    barcode: '8901234567892',
    name: 'Artisan Roast Arabica Coffee Beans (500g)',
    description: 'Medium-dark roast single origin highland Arabica whole beans.',
    category: 'Beverages',
    primaryUnit: 'Pouch',
    packagingUnit: 'Box',
    packagingMultiplier: 10,
    costPrice: 6.80,
    retailPrice: 11.99,
    wholesaleTiers: [
      { minQuantity: 10, pricePerUnit: 9.50, label: 'Box Tier (10+ pouches)' },
      { minQuantity: 50, pricePerUnit: 8.20, label: 'Cafe Bulk (50+ pouches)' },
    ],
    stockQuantity: 64,
    reorderLevel: 20,
    taxRate: 5,
    hsnCode: '0901.21',
    batches: [
      { id: 'b-301', batchNumber: 'COF-NOV-01', expiryDate: '2026-08-30', quantity: 64, costPrice: 6.80 },
    ],
    imageUrl: 'https://images.unsplash.com/photo-1559056199-641a0ac8b55e?w=300&auto=format&fit=crop&q=60',
    active: true,
  },
  {
    id: 'prod-4',
    sku: 'ELEC-MOU-01',
    barcode: '8901234567893',
    name: 'Ergonomic 2.4G Silent Wireless Mouse',
    description: 'Rechargeable dual-mode ergonomic optical mouse with 6 buttons.',
    category: 'Electronics & Tech',
    primaryUnit: 'Unit',
    packagingUnit: 'Master Carton',
    packagingMultiplier: 20,
    costPrice: 12.00,
    retailPrice: 24.99,
    wholesaleTiers: [
      { minQuantity: 10, pricePerUnit: 18.00, label: 'Wholesale Tier 1 (10-19)' },
      { minQuantity: 20, pricePerUnit: 15.50, label: 'Master Carton (20-49)' },
      { minQuantity: 50, pricePerUnit: 13.90, label: 'B2B Super Tier (50+)' },
    ],
    stockQuantity: 88,
    reorderLevel: 15,
    taxRate: 18,
    hsnCode: '8471.60',
    batches: [
      { id: 'b-401', batchNumber: 'LOT-MOU-99', expiryDate: '2030-01-01', quantity: 88, costPrice: 12.00 },
    ],
    imageUrl: 'https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?w=300&auto=format&fit=crop&q=60',
    active: true,
  },
  {
    id: 'prod-5',
    sku: 'ELEC-CAB-USBC',
    barcode: '8901234567894',
    name: 'Braided 65W Fast Charging USB-C Cable (2m)',
    description: 'Durable nylon braided high-speed sync and PD charging cable.',
    category: 'Electronics & Tech',
    primaryUnit: 'Piece',
    packagingUnit: 'Inner Box',
    packagingMultiplier: 25,
    costPrice: 2.10,
    retailPrice: 8.99,
    wholesaleTiers: [
      { minQuantity: 25, pricePerUnit: 4.80, label: 'Inner Box (25 pcs)' },
      { minQuantity: 100, pricePerUnit: 3.50, label: 'Carton (100 pcs)' },
      { minQuantity: 250, pricePerUnit: 2.90, label: 'Bulk Wholesale (250+)' },
    ],
    stockQuantity: 340,
    reorderLevel: 50,
    taxRate: 18,
    hsnCode: '8544.42',
    batches: [
      { id: 'b-501', batchNumber: 'CAB-2025-X', expiryDate: '2032-12-31', quantity: 340, costPrice: 2.10 },
    ],
    imageUrl: 'https://images.unsplash.com/photo-1583863788434-e58a36330cf0?w=300&auto=format&fit=crop&q=60',
    active: true,
  },
  {
    id: 'prod-6',
    sku: 'DRK-SPK-330',
    barcode: '8901234567895',
    name: 'Italian Sparkling Mineral Water (330ml Can)',
    description: 'Refreshing carbonated natural mountain spring water.',
    category: 'Beverages',
    primaryUnit: 'Can',
    packagingUnit: 'Case',
    packagingMultiplier: 24, // 24 cans per case
    costPrice: 0.65,
    retailPrice: 1.65,
    wholesaleTiers: [
      { minQuantity: 24, pricePerUnit: 1.10, label: 'Case of 24' },
      { minQuantity: 120, pricePerUnit: 0.92, label: '5+ Cases (120+)' },
      { minQuantity: 480, pricePerUnit: 0.80, label: 'Pallet (480+)' },
    ],
    stockQuantity: 14, // LOW STOCK TRIGGER FOR DEMO
    reorderLevel: 48,
    taxRate: 12,
    hsnCode: '2201.10',
    batches: [
      { id: 'b-601', batchNumber: 'SPK-2025-88', expiryDate: '2026-07-20', quantity: 14, costPrice: 0.65 },
    ],
    imageUrl: 'https://images.unsplash.com/photo-1622483767028-3f66f32aef97?w=300&auto=format&fit=crop&q=60',
    active: true,
  },
  {
    id: 'prod-7',
    sku: 'BAT-ALK-AA4',
    barcode: '8901234567896',
    name: 'Long-Life AA Alkaline Batteries (4-Pack)',
    description: '1.5V leak-resistant alkaline cells with 10-year shelf life.',
    category: 'Hardware & Tools',
    primaryUnit: 'Pack',
    packagingUnit: 'Display Box',
    packagingMultiplier: 12,
    costPrice: 2.20,
    retailPrice: 4.99,
    wholesaleTiers: [
      { minQuantity: 12, pricePerUnit: 3.40, label: 'Display Box (12 packs)' },
      { minQuantity: 60, pricePerUnit: 2.85, label: 'Master Box (60 packs)' },
    ],
    stockQuantity: 120,
    reorderLevel: 24,
    taxRate: 18,
    hsnCode: '8506.10',
    batches: [
      { id: 'b-701', batchNumber: 'BAT-2025-09', expiryDate: '2035-12-31', quantity: 120, costPrice: 2.20 },
    ],
    imageUrl: 'https://images.unsplash.com/photo-1619725002198-6a689b72f41d?w=300&auto=format&fit=crop&q=60',
    active: true,
  },
  {
    id: 'prod-8',
    sku: 'DISP-GLV-100',
    barcode: '8901234567897',
    name: 'Nitrile Heavy-Duty Disposable Gloves (Box of 100)',
    description: 'Powder-free, textured grip medical and food grade gloves.',
    category: 'Safety & Hygiene',
    primaryUnit: 'Box',
    packagingUnit: 'Master Carton',
    packagingMultiplier: 10,
    costPrice: 6.40,
    retailPrice: 12.50,
    wholesaleTiers: [
      { minQuantity: 10, pricePerUnit: 9.80, label: 'Carton (10 boxes)' },
      { minQuantity: 50, pricePerUnit: 8.20, label: 'Pallet (50+ boxes)' },
    ],
    stockQuantity: 45,
    reorderLevel: 10,
    taxRate: 12,
    hsnCode: '4015.19',
    batches: [
      { id: 'b-801', batchNumber: 'GLV-NIT-52', expiryDate: '2029-05-18', quantity: 45, costPrice: 6.40 },
    ],
    imageUrl: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=300&auto=format&fit=crop&q=60',
    active: true,
  },
];

export const initialCustomers: Customer[] = [
  {
    id: 'cust-walkin',
    type: 'retail',
    name: 'Walk-in Cash Customer',
    phone: '9999999999',
    tier: 'standard',
    creditLimit: 0,
    currentBalance: 0,
    paymentTerms: 'cod',
    createdAt: '2025-01-01',
  },
  {
    id: 'cust-b2b-1',
    type: 'wholesale',
    name: 'David Vance',
    companyName: 'Apex HyperMart Chain Inc.',
    phone: '+1 (555) 723-8811',
    email: 'purchasing@apexhypermart.com',
    address: {
      street: '1240 Commercial Way, Warehouse 4',
      city: 'Metro City',
      state: 'NY',
      postalCode: '10025',
      country: 'USA',
    },
    taxId: 'TAX-CORP-992144-A',
    tier: 'platinum',
    creditLimit: 25000,
    currentBalance: 4620.50,
    paymentTerms: 'net_30',
    notes: 'Key regional supermarket account. Eligible for maximum tier discounts.',
    createdAt: '2025-01-15',
  },
  {
    id: 'cust-b2b-2',
    type: 'wholesale',
    name: 'Marcus Brody',
    companyName: 'Brody Convenience Marts',
    phone: '+1 (555) 438-1920',
    email: 'marcus@brodymarts.net',
    address: {
      street: '450 West 8th Avenue',
      city: 'Metro City',
      state: 'NY',
      postalCode: '10018',
      country: 'USA',
    },
    taxId: 'TAX-CORP-331084-B',
    tier: 'gold',
    creditLimit: 10000,
    currentBalance: 2150.00,
    paymentTerms: 'net_15',
    notes: 'Fast moving beverage and snack orders every Tuesday.',
    createdAt: '2025-02-01',
  },
  {
    id: 'cust-b2b-3',
    type: 'wholesale',
    name: 'Elena Rostova',
    companyName: 'Blue Harbor Bistro & Cafe',
    phone: '+1 (555) 902-3142',
    email: 'supplies@blueharbor.com',
    address: {
      street: '88 Pier Walk Road',
      city: 'Coastline Harbor',
      state: 'NY',
      postalCode: '11050',
      country: 'USA',
    },
    taxId: 'TAX-RESTAURANT-7734',
    tier: 'silver',
    creditLimit: 5000,
    currentBalance: 840.00,
    paymentTerms: 'net_7',
    notes: 'Coffee beans and olive oil bulk buyer.',
    createdAt: '2025-03-10',
  },
  {
    id: 'cust-ret-1',
    type: 'retail',
    name: 'Sarah Jenkins',
    phone: '+1 (555) 662-9102',
    email: 'sarah.j@gmail.com',
    tier: 'gold',
    creditLimit: 0,
    currentBalance: 0,
    paymentTerms: 'cod',
    loyaltyPoints: 480,
    createdAt: '2025-02-14',
  },
  {
    id: 'cust-ret-2',
    type: 'retail',
    name: 'Michael Chang',
    phone: '+1 (555) 301-8472',
    email: 'm.chang@yahoo.com',
    tier: 'standard',
    creditLimit: 0,
    currentBalance: 0,
    paymentTerms: 'cod',
    loyaltyPoints: 125,
    createdAt: '2025-04-02',
  },
];

export const initialSuppliers: Supplier[] = [
  {
    id: 'sup-1',
    name: 'Continental Agro Commodities Ltd.',
    contactPerson: 'Harish Patel',
    phone: '+1 (555) 880-1234',
    email: 'orders@continentalagro.com',
    address: 'Warehouse Hub 8, Agri Park, NJ',
    taxId: 'TAX-SUP-88310',
    paymentTerms: 'Net 30',
    totalPurchased: 45000,
    outstandingBalance: 6200,
  },
  {
    id: 'sup-2',
    name: 'Nexis Tech & Hardware Imports',
    contactPerson: 'Chloe Chen',
    phone: '+1 (555) 991-4455',
    email: 'sales@nexisimports.com',
    address: 'Dock 12, Terminal Blvd, CA',
    taxId: 'TAX-SUP-55190',
    paymentTerms: 'Net 15',
    totalPurchased: 32000,
    outstandingBalance: 3400,
  },
  {
    id: 'sup-3',
    name: 'Alpine Spring Beverages Bottling Co.',
    contactPerson: 'Marco Valente',
    phone: '+1 (555) 441-2300',
    email: 'marco@alpinespring.it',
    address: 'Via Delle Alpi 44, Milan, Italy',
    taxId: 'EU-IT-9923841',
    paymentTerms: 'Net 60',
    totalPurchased: 18500,
    outstandingBalance: 1200,
  },
];

export const initialInvoices: Invoice[] = [
  {
    id: 'inv-whl-001',
    invoiceNumber: 'INV-WHL-2025-101',
    type: 'wholesale',
    date: '2025-05-10',
    dueDate: '2025-06-09',
    customerId: 'cust-b2b-1',
    customerName: 'Apex HyperMart Chain Inc.',
    customerPhone: '+1 (555) 723-8811',
    customerTaxId: 'TAX-CORP-992144-A',
    billingAddress: '1240 Commercial Way, Warehouse 4, Metro City',
    items: [
      {
        id: 'item-1',
        productId: 'prod-1',
        productName: 'Premium Royal Basmati Rice (5kg)',
        sku: 'RICE-BAS-05',
        unitType: 'packaging',
        unitName: 'Carton (6 bags)',
        packagingMultiplier: 6,
        quantity: 10, // 10 cartons = 60 bags -> activates pallet tier $9.95/bag * 6 = $59.70/carton
        totalPrimaryUnits: 60,
        unitPrice: 59.70,
        costPrice: 55.20,
        discountPercentage: 0,
        taxRate: 5,
        taxAmount: 29.85,
        subtotal: 597.00,
        total: 626.85,
      },
      {
        id: 'item-2',
        productId: 'prod-2',
        productName: 'Cold-Pressed Extra Virgin Olive Oil (1L)',
        sku: 'OIL-OLV-1L',
        unitType: 'packaging',
        unitName: 'Crate (12 btl)',
        packagingMultiplier: 12,
        quantity: 4, // 48 bottles -> activates wholesale tier $13.50/btl * 12 = $162.00/crate
        totalPrimaryUnits: 48,
        unitPrice: 162.00,
        costPrice: 138.00,
        discountPercentage: 0,
        taxRate: 5,
        taxAmount: 32.40,
        subtotal: 648.00,
        total: 680.40,
      },
      {
        id: 'item-3',
        productId: 'prod-5',
        productName: 'Braided 65W Fast Charging USB-C Cable (2m)',
        sku: 'ELEC-CAB-USBC',
        unitType: 'packaging',
        unitName: 'Inner Box (25 pcs)',
        packagingMultiplier: 25,
        quantity: 4, // 100 pcs -> activates carton tier $3.50 * 25 = $87.50
        totalPrimaryUnits: 100,
        unitPrice: 87.50,
        costPrice: 52.50,
        discountPercentage: 5,
        taxRate: 18,
        taxAmount: 59.85,
        subtotal: 332.50,
        total: 392.35,
      },
    ],
    subtotal: 1577.50,
    discountTotal: 17.50,
    taxTotal: 122.10,
    roundOff: 0,
    grandTotal: 1699.60,
    paidAmount: 500.00,
    dueAmount: 1199.60,
    paymentStatus: 'partial',
    status: 'completed',
    payments: [
      { id: 'pay-1', method: 'bank_transfer', amount: 500.00, reference: 'WIRE-88910', date: '2025-05-10' },
    ],
    cashierName: 'Admin Desk',
    notes: 'Order packed in pallet shrink-wrap. Delivery via Express Haul.',
    createdAt: '2025-05-10T14:30:00Z',
  },
  {
    id: 'inv-ret-001',
    invoiceNumber: 'INV-RET-2025-001',
    type: 'retail',
    date: '2025-05-12',
    customerId: 'cust-ret-1',
    customerName: 'Sarah Jenkins',
    customerPhone: '+1 (555) 662-9102',
    items: [
      {
        id: 'ritem-1',
        productId: 'prod-1',
        productName: 'Premium Royal Basmati Rice (5kg)',
        sku: 'RICE-BAS-05',
        unitType: 'primary',
        unitName: 'Bag',
        packagingMultiplier: 1,
        quantity: 1,
        totalPrimaryUnits: 1,
        unitPrice: 14.50,
        costPrice: 9.20,
        discountPercentage: 0,
        taxRate: 5,
        taxAmount: 0.73,
        subtotal: 14.50,
        total: 15.23,
      },
      {
        id: 'ritem-2',
        productId: 'prod-3',
        productName: 'Artisan Roast Arabica Coffee Beans (500g)',
        sku: 'COF-ARB-500',
        unitType: 'primary',
        unitName: 'Pouch',
        packagingMultiplier: 1,
        quantity: 2,
        totalPrimaryUnits: 2,
        unitPrice: 11.99,
        costPrice: 6.80,
        discountPercentage: 10,
        taxRate: 5,
        taxAmount: 1.08,
        subtotal: 21.58,
        total: 22.66,
      },
      {
        id: 'ritem-3',
        productId: 'prod-7',
        productName: 'Long-Life AA Alkaline Batteries (4-Pack)',
        sku: 'BAT-ALK-AA4',
        unitType: 'primary',
        unitName: 'Pack',
        packagingMultiplier: 1,
        quantity: 1,
        totalPrimaryUnits: 1,
        unitPrice: 4.99,
        costPrice: 2.20,
        discountPercentage: 0,
        taxRate: 18,
        taxAmount: 0.90,
        subtotal: 4.99,
        total: 5.89,
      },
    ],
    subtotal: 41.07,
    discountTotal: 2.40,
    taxTotal: 2.71,
    roundOff: 0.02,
    grandTotal: 43.80,
    paidAmount: 43.80,
    dueAmount: 0,
    paymentStatus: 'paid',
    status: 'completed',
    payments: [
      { id: 'rpay-1', method: 'card', amount: 43.80, reference: 'VISA-AUTH-7712', date: '2025-05-12' },
    ],
    cashierName: 'POS Counter 1',
    createdAt: '2025-05-12T11:15:00Z',
  },
];

export const initialLedgerEntries: LedgerEntry[] = [
  {
    id: 'led-1',
    partyType: 'customer',
    partyId: 'cust-b2b-1',
    partyName: 'Apex HyperMart Chain Inc.',
    date: '2025-05-01',
    type: 'invoice',
    referenceId: 'INV-WHL-2025-090',
    description: 'Bulk Grocery Dispatch',
    debit: 3420.90,
    credit: 0,
    runningBalance: 3420.90,
  },
  {
    id: 'led-2',
    partyType: 'customer',
    partyId: 'cust-b2b-1',
    partyName: 'Apex HyperMart Chain Inc.',
    date: '2025-05-05',
    type: 'payment_received',
    referenceId: 'WIRE-77312',
    description: 'Bank Wire Payment for April Billings',
    debit: 0,
    credit: 3420.90,
    runningBalance: 0.00,
  },
  {
    id: 'led-3',
    partyType: 'customer',
    partyId: 'cust-b2b-1',
    partyName: 'Apex HyperMart Chain Inc.',
    date: '2025-05-10',
    type: 'invoice',
    referenceId: 'INV-WHL-2025-101',
    description: 'B2B Pallet Dispatch (Invoice #101)',
    debit: 1699.60,
    credit: 0,
    runningBalance: 1699.60,
  },
  {
    id: 'led-4',
    partyType: 'customer',
    partyId: 'cust-b2b-1',
    partyName: 'Apex HyperMart Chain Inc.',
    date: '2025-05-10',
    type: 'payment_received',
    referenceId: 'WIRE-88910',
    description: 'Advance Partial Wire Transfer',
    debit: 0,
    credit: 500.00,
    runningBalance: 1199.60,
  },
  {
    id: 'led-5',
    partyType: 'customer',
    partyId: 'cust-b2b-2',
    partyName: 'Brody Convenience Marts',
    date: '2025-05-08',
    type: 'invoice',
    referenceId: 'INV-WHL-2025-098',
    description: 'Beverages & Electronics Restock',
    debit: 2150.00,
    credit: 0,
    runningBalance: 2150.00,
  },
];

export const initialPurchaseOrders: PurchaseOrder[] = [
  {
    id: 'po-101',
    poNumber: 'PO-2025-045',
    supplierId: 'sup-1',
    supplierName: 'Continental Agro Commodities Ltd.',
    orderDate: '2025-05-01',
    expectedDate: '2025-05-15',
    items: [
      {
        productId: 'prod-1',
        productName: 'Premium Royal Basmati Rice (5kg)',
        sku: 'RICE-BAS-05',
        unit: 'Carton (6 bags)',
        quantity: 25,
        unitCost: 54.00,
        taxRate: 5,
        total: 1417.50,
      },
    ],
    subtotal: 1350.00,
    taxTotal: 67.50,
    grandTotal: 1417.50,
    status: 'received',
    paymentStatus: 'paid',
    paidAmount: 1417.50,
    notes: 'Warehouse dock delivery received in good condition.',
  },
  {
    id: 'po-102',
    poNumber: 'PO-2025-048',
    supplierId: 'sup-3',
    supplierName: 'Alpine Spring Beverages Bottling Co.',
    orderDate: '2025-05-08',
    expectedDate: '2025-05-20',
    items: [
      {
        productId: 'prod-6',
        productName: 'Italian Sparkling Mineral Water (330ml Can)',
        sku: 'DRK-SPK-330',
        unit: 'Case of 24',
        quantity: 50,
        unitCost: 15.60,
        taxRate: 12,
        total: 873.60,
      },
    ],
    subtotal: 780.00,
    taxTotal: 93.60,
    grandTotal: 873.60,
    status: 'ordered',
    paymentStatus: 'unpaid',
    paidAmount: 0,
    notes: 'Urgent restock to alleviate low stock condition.',
  },
];
